//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bruger
    {
        public int BrugerID { get; set; }
        public string ForNavn { get; set; }
        public string EfterNavn { get; set; }
        public string Adgangskode { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> status { get; set; }
        public string Adresse { get; set; }
        public string Postnr { get; set; }
        public string By { get; set; }
        public string Telefon { get; set; }
        public string Land { get; set; }
    }
}
