//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduktTabel
    {
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public string ProduktBeskrivelse { get; set; }
        public string ProduktNavn { get; set; }
        public string Pris { get; set; }
    }
}
